services:
  - type: web
    name: neighbornet-backend
    runtime: docker
    rootDir: backend
    envVars:
      - key: DB_URL
        fromDatabase:
          name: neighbornet-mysql
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: neighbornet-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: neighbornet-mysql
          property: password
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 3600000
      - key: JWT_REFRESH_EXPIRATION
        value: 86400000
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_SECRET
        sync: false
      - key: HMS_ACCESS_KEY
        sync: false
      - key: HMS_APP_SECRET
        sync: false
      - key: HMS_TEMPLATE_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false